# Generated by Django 3.2.4 on 2021-06-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorate', models.CharField(choices=[('Public-1', 'Public-1'), ('Public-2', 'Public-2'), ('Public-3', 'Public-3'), ('Private-1', 'Private-1'), ('Private-2', 'Private-2')], max_length=10)),
                ('ambm', models.CharField(max_length=30)),
                ('pid', models.CharField(max_length=10, unique=True)),
                ('client', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=50)),
                ('rental', models.BooleanField(default=False)),
                ('level', models.CharField(max_length=2)),
                ('order_val', models.DecimalField(decimal_places=2, max_digits=17)),
                ('gpm', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
