# Generated by Django 3.2.4 on 2021-06-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='ambm',
            field=models.CharField(max_length=30, verbose_name='AM/BM Name'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='bast_dd',
            field=models.DateField(verbose_name='BAST Date'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='client',
            field=models.CharField(max_length=50, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='directorate',
            field=models.CharField(choices=[('Public-1', 'Public-1'), ('Public-2', 'Public-2'), ('Public-3', 'Public-3'), ('Private-1', 'Private-1'), ('Private-2', 'Private-2')], max_length=10, verbose_name='Directorate'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='gpm',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='GPM (%)'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='level',
            field=models.CharField(max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='nmonth',
            field=models.IntegerField(verbose_name='x Months'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='order_dd',
            field=models.DateField(verbose_name='SO Booking'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='order_val',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='pid',
            field=models.CharField(max_length=10, unique=True, verbose_name='Prospect ID'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='project',
            field=models.CharField(max_length=50, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='rental',
            field=models.BooleanField(default=False, verbose_name='Rental/Managed Service'),
        ),
    ]
