# Generated by Django 3.2.4 on 2021-06-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210617_0539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['directorate', 'order_dd', 'level', '-order_val'], 'verbose_name_plural': 'Sales Pipelines'},
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='directorate',
            field=models.CharField(choices=[('Pub-1', 'Pub-1'), ('Pub-2', 'Pub-2'), ('Pub-3', 'Pub-3'), ('Pri-1', 'Pri-1'), ('Pri-2', 'Pri-2')], max_length=10, verbose_name='Directorate'),
        ),
    ]
