# Generated by Django 3.2.4 on 2021-06-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210606_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='order_dd',
            field=models.DateField(verbose_name='SO Booking DD'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='order_val',
            field=models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Value'),
        ),
    ]
