# Generated by Django 3.2.4 on 2021-06-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210606_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='rental',
            field=models.BooleanField(default=False, verbose_name='Rental/Mngd Service'),
        ),
    ]
