# Generated by Django 3.2.4 on 2021-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210619_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='rental',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='onetime',
            field=models.BooleanField(default=True, verbose_name='One-time Project'),
        ),
    ]
