# Generated by Django 3.2.4 on 2021-06-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_pipeline_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='level',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E')], max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='nmonth',
            field=models.IntegerField(default=1, verbose_name='x Months'),
        ),
    ]
